<?php

return [
    'date_format'         => 'd/m/Y',
    'time_format'         => 'H:i:s',
    'primary_language'    => 'en',
    'available_languages' => [
        'en'      => 'English',
        'id'      => 'Bahasa / Indonesia',
        'ru'      => 'Russian',
        'tr'      => 'Turkish',
        'it'      => 'Italian',
        'ar'      => 'Arabic',
        'pt'      => 'Portuguese',
        'es'      => 'Spanish',
        'pt-br'   => 'Brazilian Portuguese',
        'de'      => 'German',
        'nl'      => 'Dutch',
        'hu'      => 'Hungarian',
        'ca'      => 'Catalan',
        'se'      => 'Swedish',
        'zh'      => 'Traditional Chinese',
        'pl'      => 'Polish',
        'mn'      => 'Mongolian',
        'ua'      => 'Ukranian',
        'fr'      => 'French',
        'gr'      => 'Greek',
        'fa'      => 'Persian',
        'lt'      => 'Lithuanian',
        'by'      => 'Belarusian',
        'fi'      => 'Finnish',
        'zh-Hans' => 'Chinese',
        'he'      => 'Hebrew',
        'hi'      => 'Hindi',
        'ro'      => 'Romanian',
        'bg'      => 'Bulgarian',
        'dk'      => 'Danish',
    ],
];
